name: Linting Examples

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: get node modules
      run: npm ci
      env:
        CI: true
    - name: lint examples
      run: npm run lint:samples
