name: Testing

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get node modules
      run: npm ci
      env:
        CI: true
    - name: build and test
      run: npm test
      env:
        CI: true
