name: Testing

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get node modules
      run: npm ci
      env:
        CI: true
    - name: build and test
      run: npm test
      env:
        CI: true
